
class TradeExitReason:
  SL_HIT = "SL HIT"
  TRAIL_SL_HIT = "TRAIL SL HIT"
  TARGET_HIT = "TARGET HIT"
  SQUARE_OFF = "SQUARE OFF"
  SL_CANCELLED = "SL CANCELLED"
  TARGET_CANCELLED = "TARGET CANCELLED"
  STRATEGY_SL_HIT = "STGY SL HIT"
  STRATEGY_TRAIL_SL_HIT = "STGY TRAIL SL HIT"
  STRATEGY_TARGET_HIT = "STGY TARGET HIT"
  